apiVersion: v1
kind: Namespace
metadata:
  name:: graphql-layer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  namespace: graphql-layer
spec:
  selector:
    matchLabels:
      app: graphql
  replicas: 2
  template:
    metadata:
      labels:
        app: graphql
    spec:
      containers:
        - name: graphql
          image: registry.gitlab.com/slackbot1/bot-backend/main:latest
          ports:
            - containerPort: 4000
