version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.16.9
  gcp-cloud-run: livup/gcp-cloud-run@1.0.32
parameters:
  backend:
    type: boolean
    default: true
  bot:
    type: boolean
    default: true
  web:
    type: boolean
    default: false
jobs:
  build_deploy_container:
    parameters:
      package_name:
        type: string
      dockerfile:
        type: string
        default: Dockerfile
      dlc:
        type: boolean
        default: true
    machine:
      docker_layer_caching: << parameters.dlc >>
      resource_class: medium
      image: ubuntu-2004:current
    working_directory: ~/project/
    steps:
      - checkout
      - gcp-gcr/gcr-auth
      - gcp-gcr/build-image:
          image: << parameters.package_name >>
          dockerfile: << parameters.dockerfile >>
          extra_build_args: --build-arg SHA1=$CIRCLE_SHA1 --build-arg APP=<< parameters.package_name >>
          tag: $CIRCLE_SHA1
      - gcp-gcr/push-image:
          image: << parameters.package_name >>
          tag: $CIRCLE_SHA1
      - gcp-gcr/tag-image:
          image: << parameters.package_name >>
          source-tag: $CIRCLE_SHA1
          target-tag: latest
  deploy_container:
    docker:
      - image: cimg/base:stable
    working_directory: ~/project/
    parameters:
      package_name:
        type: string
      dockerfile:
        type: string
        default: Dockerfile
      dlc:
        type: boolean
        default: true
    steps:
      - gcp-cloud-run/init
      - gcp-cloud-run/deploy:
          image: gcr.io/slack-battle-bot/<< parameters.package_name >>:$CIRCLE_SHA1
          platform: managed
          region: us-west1
          service-name: << parameters.package_name >>
          unauthenticated: true

workflows:
  backend:
    when: << pipeline.parameters.backend >>
    jobs:
      - build_deploy_container:
          package_name: backend
          context: EnvVariables
          filters:
            branches:
              only:
                - master
      - deploy_container:
          requires:
            - build_deploy_container
          package_name: backend
          context: EnvVariables
          filters:
            branches:
              only:
                - master
  bot:
    when: << pipeline.parameters.bot >>
    jobs:
      - build_deploy_container:
          package_name: bot
          context: EnvVariables
          dlc: true
          filters:
            branches:
              only:
                - master
      - deploy_container:
          requires:
            - build_deploy_container
          package_name: bot
          context: EnvVariables
          filters:
            branches:
              only:
                - master
  web:
    when: << pipeline.parameters.web >>
    jobs:
      - build_deploy_container:
          package_name: web
          name: web
          context: EnvVariables
          dockerfile: packages/web/Dockerfile
          filters:
            branches:
              only:
                - master
