gitops:
  manifest_projects:
    # The `id` is the path to the Git repository holding your manifest files
    - id: 'slackbot1/bot-backend'
      default_namespace: graphql-layer
      paths:
        - glob: 'manifest.yml'
